version: "3"
services:
  db:
    container_name: go-db
    build: ./db
    env_file: ../.env
    ports: 
      - '5432:5432'
    networks:
      - db_default
    volumes:
      - ./db:/docker-entrypoint-initdb.d

networks:
  db_default:
    external: true
